project:
  type: website

website:
  title: "Intro to DA"
  favicon: favicon-big.png
  navbar:
    left:
      - text: "Slides"
        menu: 
          - href: slides-dplyr.qmd
            text: Filtering, Transforming, and Summarizing
      - text: "Course Units"
        menu: 
            - href: intro.qmd
              text: "1. Introduction: Visualizing Data with R (not yet written)"
            - href: basics.qmd
              text: "2. Basics: Working with R and Quarto (not yet written)"
            - href: filter-transform-summarize.qmd
              text: "3. Filtering, Transforming, and Summarizing Tables"
            - href: import-pivot-join.qmd
              text: "4. Importing, Pivoting, and Combining Data Sets"
            - href: exam-review.qmd
              text: "Unit 3 Exam Review"
  page-footer: "Copyright 2022, James Clawson" 
  repo-url: https://github.com/jmclawson/gramda-site
  repo-actions: [source]

format:
  html:
    theme: [cosmo, custom.scss]
    highlight-style: "atom-one"
    code-link: true
    css: styles.css
    toc: true
    toc-location: left
    number-sections: true
    df-print: paged

editor: visual

