project:
  type: website

website:
  title: "Intro to DA"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Slides"
        menu: 
          - href: intro-to-text-analysis.html
            text: Intro to Text Analysis
      - text: "Course Units"
        menu: 
            - href: intro.qmd
              text: "1. Introduction: Visualizing Data with R"
            - href: basics.qmd
              text: "2. Basics: Working with R and Quarto"
            - href: dplyr.qmd
              text: "3. dplyr: Filtering, Transforming, and Summarizing Tables"
            - href: data.qmd
              text: "4. Importing, Combining, and Exporting Data Sets"
      - about.qmd
  page-footer: "Copyright 2022, James Clawson" 
  repo-url: https://github.com/jmclawson/gramda-teaching-website
  repo-actions: [edit, issue]

format:
  html:
    theme: [cosmo, custom.scss]
    highlight-style: "atom-one"
    # theme: journal
    # theme: sandstone
    # theme: simplex
    # theme: sketchy
    # theme: solar
    # theme: superhero
    # theme: zephyr
    css: styles.css
    toc: true

editor: visual

